package us.zoom.web.calendar.api.view;

import us.zoom.web.calendar.api.enums.ConferenceSolutionType;

import java.util.HashMap;
import java.util.Map;

/**
 * @author George
 * @date 2019/11/25 11:24
 */
public class ConferenceInfo {
    /**
     * @see ConferenceSolutionType
     */
    private Integer conferenceProvider = ConferenceSolutionType.NONE.getCode();

    /**
     * generated by DialStringUtil
     * @see //ConferenceDialMethod
     */
    private Integer preferredDialMethod;

    /**
     * Meeting ID of Zoom or other conference solutions
     */
    private String meetingId;

    /**
     * Meeting password, encrypted
     */
    private String meetingPassword;

    /**
     * Generated join dial string for the conference, could be SIP,H323,HTTP URL, depends on dial method
     */
    private String dialString;


    private String domainName;

    /**
     * customized properties, such as PSTN, Generic SIP URL ...
     * TODO: available keys to implement: pstn, sip_uri, h323_uri
     */
    private Map<String, String> properties = new HashMap<>(5);
}
